version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    depends_on:
      - mysqldb
  
  mysqldb:
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=passme
      - MYSQL_DATABASE=user
      - MYSQL_USER=root
    ports:
      - "3307:3306"